export const scratcher_good = [
  "Ayy, you won some scratch!",
  "Nice! You won some money!",
  "Oh, yeah, you like that prize money, huh?",
  "Winner!",
  "Congrats on the win!",
  "Great buy!",
  "You won! I knew you could do it!",
  "This could change everything!",
  "Nice luck you got there!",
  "Don't spend those winnings all in one place!",
  "Go buy yourself something nice!",
  "You... WON!",
  "WHOO-HOO! THAT'S A WINNER!",
  "Noice - you won a lil somethin' something'",
  "Gonna have to keep this from the fam!",
  "Keep the good times rollin'!",
];

export const scratcher_bad = [
  "Oh no! You lost!",
  "Can't all be winners!",
  "Better luck next time!",
  "No bueno, amigo :(",
  "It happens to the best of 'em",
  "It's ok... I won't tell anyone",
  "Try again!",
  "It happens!",
  "Sorry, but that one... LOST!",
  "Hey, the odds can't always be in your favor",
  "Could be worse, am I right?",
];
